### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by andrew** [tbenett/ruby-ipfs-api#49]
Some methods described in the docs no longer work, such as `Ipfs::Client::addresses`. 

Would you prefer I update the docs to match the code on the master branch, or fix the code to match the docs?

**Comment by tbenett** [comment]
Hey Andrew :wave:

Documentation was out of date for some time on `master` :(
Actually, all the up-to-date version was on branch `documentation` that I just merged.

You can take a look.

**Comment by andrew** [comment]
Thanks!

**Comment by tbenett** [comment]
I edited my post

**Comment by andrew** [comment]
👍

**Comment by andrew** [comment]
Feel free to close when ready

**Comment by tbenett** [comment]
ok @andrew the doc has been uploaded correctly. It can be seen [here](https://www.rubydoc.info/gems/ruby-ipfs-api/)
